name: Docker Image CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tannerk/budgetmax-api:$(date +%s)

    - name: Login to Docker
      run: docker login -u tannerk -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker
      run: docker push tannerk/budgetmax-api:$(date +%s)

      
   
